'use client'
import { useTransition } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { toast } from 'sonner'
import { adjustStockAction } from '@/actions/products'
import { stockAdjustmentSchema } from '@/lib/validations/product'
import { todayInputValue } from '@/lib/dates'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
export function StockAdjustForm({productId,onDone}:{productId:string;onDone:()=>void}){const [pending,startTransition]=useTransition();const f=useForm<any>({resolver:zodResolver(stockAdjustmentSchema),defaultValues:{productId,type:'ADD',quantity:1,date:todayInputValue(),notes:''}});return <form className="space-y-4" onSubmit={f.handleSubmit(d=>startTransition(async()=>{const r=await adjustStockAction(d);if(!r.success){toast.error(r.error);return}toast.success(r.message??'Stock updated');onDone()}))}><input type="hidden" {...f.register('productId')}/><select className="h-10 w-full rounded-md border bg-transparent px-3" {...f.register('type')}><option value="ADD">Add stock</option><option value="REDUCE">Reduce stock</option></select><Input type="number" min="1" {...f.register('quantity',{valueAsNumber:true})}/><Input type="date" {...f.register('date')}/><Textarea placeholder="Reason or notes" {...f.register('notes')}/><Button disabled={pending} className="w-full">{pending?'Updating…':'Update stock'}</Button></form>}
